version: '3.8'

services:
  rtstt:
    build:
      context: .
      target: gpu
    image: rtstt
    container_name: rtstt
    volumes:
      - ./transcriber:/app/transcriber
      - ./browserClientDemo:/app/browserClientDemo
      - cache:/root/.cache
    ports:
      - "9001:9001"

    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

volumes:
  cache:
#  nginx:
#    image: nginx:latest
#    container_name: nginx_web
#    ports:
#      - "8081:80"
#    volumes:
#      - ./example_browserclient:/usr/share/nginx/html
#
#volumes:
#  cache: